server:
  port: 8092


spring:
  application:
    name: infraestructura
  datasource:
    mongodb:
      url: mongodb+srv://rzagza039:a**039##a@cluster0.iaacx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
  config:
    import: optional:configserver:http://localhost:8888
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration  
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka         