server:
  port: 8092

spring:
  application:
    name: infraestructura
  data:
    mongodb:
      uri: mongodb+srv://rzagza039:1234@cluster0.iaacx.mongodb.net/Microservice?retryWrites=true&w=majority&appName=Cluster0
  config:
    import: optional:configserver:http://localhost:8888
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration  

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10  
    leaseExpirationDurationInSeconds: 30
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
